<?php

/**
 * @file
 * W3CSS Paragraphs.
 *
 * Filename:     w3css_paragraphs.module
 * Website:      https://www.flashwebcenter.com
 * Description:  template.
 * Developer:    Alaa Haddad https://www.alaahaddad.com.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function w3css_paragraphs_help($route_name, RouteMatchInterface $route_match) {

  switch ($route_name) {
    case 'help.page.w3css_paragraphs':
      $text = file_get_contents(__DIR__ . "/README.md");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      // Use the Markdown filter to render the README.
      $filter_manager = \Drupal::service('plugin.manager.filter');
      $settings = \Drupal::configFactory()
        ->get('markdown.settings')
        ->getRawData();
      $config = ['settings' => $settings];
      $filter = $filter_manager->createInstance('markdown', $config);
      return $filter->process($text, 'en');
  }
  return NULL;
}

/**
 * Implements hook_preprocess_page().
 */
function w3css_paragraphs_preprocess_page(&$variables) {
  /** @var \Drupal\Core\Routing\AdminContext $admin_context */
  $admin_context = \Drupal::service('router.admin_context');
  if ($admin_context->isAdminRoute()) {
    $variables['#attached']['library'][] = "w3css_paragraphs/w3css-paragraphs-admin";
  }
}

/**
 * Implements hook_theme().
 */
function w3css_paragraphs_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__default' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__w3css_card' => [
      'base hook' => 'paragraph',
    ],
    'paragraph__w3css_image' => [
      'base hook' => 'paragraph',
    ],
    'field__entity_reference_revisions' => [
      'base hook' => 'paragraph',
    ],

  ];
}
